mongodb:
  auth:
    rootPassword: golution
    username: goboolean
    password: password
    database: goboolean-stock
    replicaSetKey: password
  
  architecture: standalone
  useStatefulSet: true
  service:
    type: ClusterIP

kafka:
  auth:
    enabled: false
  sasl:
    interbroker:
      password: password
    controller:
      password: password
  broker:
    replicaCount: 3
  kraft:
    enabled: true
    clusterId: fMCL8kv1SWm87L_Md-I2hg

etcd:
  replicaCount: 3
  auth:
    rbac:
      create: False

postgresql:
  primary:
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    initdb:
      scriptsConfigMap: postgresql-init-script
  auth:
    username: goboolean
    password: password
    database: goboolean

kafka-connect:
  replicaCount: 2

  extraVolumeMounts:
  - name: plugin
    mountPath: /usr/share/confluent-hub-components
  extraVolumes:
    - name: plugin
      emptyDir: {}
  initContainers:
    - name: init-plugin
      image: confluentinc/cp-kafka-connect:7.2.2
      command:
        - sh
        - -c
        - confluent-hub install mongodb/kafka-connect-mongodb:1.8.0 --no-prompt
      volumeMounts:
        - name: plugin
          mountPath: /usr/share/confluent-hub-components

  kafka:
    create: false
  schema-registry:
    create: false
  configMapPairs:
    CONNECT_BOOTSTRAP_SERVERS: "fetch-system-kafka:9092"

  livenessProbe:
    initialDelaySeconds: 240
    periodSeconds: 30
    timeoutSeconds: 30
  readinessProbe:
    initialDelaySeconds: 240
    periodSeconds: 30
    timeoutSeconds: 30

  resources:
    requests:
      cpu: 1000m
      memory: 3Gi
    limits:
      cpu: 1000m
      memory: 3Gi