mongodb:
  auth:
    rootPassword: golution
    username: goboolean
    password: golution
    database: goboolean-stock
  architecture: replicaset
  replicaSetName: rs0
  replicas:
    secondary: 2
  arbiter:
    enabled: false

kafka:
  auth:
    enabled: false
  sasl:
    interbroker:
      password: password
    controller:
      password: password
  broker:
    replicaCount: 3
  kraft:
    enabled: true
    clusterId: fMCL8kv1SWm87L_Md-I2hg

opentelemetry-collector:
  mode: deployment

  ports:
    otlp:
      enabled: true
      containerPort: 4317
      servicePort: 4317
      hostPort: 4317
      protocol: TCP
      appProtocol: grpc
    otlp-http:
      enabled: false
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false
    metrics:
      enabled: true
      containerPort: 8888
      servicePort: 8888
      protocol: TCP

  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets:
                    - ${env:MY_POD_IP}:8888
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
