apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fetch-system-app-chart.fullname" . }}-etcd
spec:
  replicas: {{ .Values.etcd.replicas }}
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: "{{ .Values.etcd.repository }}:{{ .Values.etcd.tag }}"          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer