apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fetch-system-app-chart.fullname" . }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.repository }}:{{ .Values.worker.tag }}"