name: Test & Build Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt environment variables
        run: |
          echo "${{ secrets.ENV }}" > deploy/.env

      - name: Run tests
        run: |
          make test-app

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & push retriever image
        run: |
          make build-retriever-app

      - name: Build & push preparer image
        run: |
          make build-preparer-app