name: Deploy

on:
  push:
    branches:
      - feature/deploy

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & push preparer image
        run: |
          make build-preparer-app